language: java
install: gradle -q assemble
script:
  - set -o pipefail; gradle check | sed 's/\e\[?.*?[\@-~]//g'
  - chmod a+x travis/build2.sh
  - ./travis/build2.sh
  - chmod a+x travis/post_build.sh
  - ./travis/post_build.sh
jdk:
  - oraclejdk7
  - oraclejdk8
branches:
  except:
    - gh-pages
env:
  global:
    - secure: "I8awdba2QYgO+vKmbsIa10L7dGPpcvt/l0sfE+NH2On4ZtBFuX7X4tFncmWizHhrqa0xvoAEl8hZFZ6+RjbAOzd9kDLfdHevLVv6z8VQusvY58GbAHPP0h4yd4PA0YsSeiLv1F7X7bCH6weZo16t42lVh4NrAS2XHqSOOvMyAWo="
    - DOCS_BRANCH="release"
    - GEN_APIDOCS="gradle javadoc"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install build-essential curl git python-setuptools ruby
  - git clone https://github.com/Linuxbrew/linuxbrew.git ~/.linuxbrew
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - brew install redis

notifications:
  slack: puniverse:OsnbakHrYeTcLyalVgtUeI4F
