sudo: required
language: java
install: gradle -q assemble
script: set -o pipefail; gradle -i check | sed 's/\e\[?.*?[\@-~]//g'
jdk:
  - oraclejdk7
  - oraclejdk8
branches:
  except:
    - gh-pages
env:
  global:
    - secure: "I8awdba2QYgO+vKmbsIa10L7dGPpcvt/l0sfE+NH2On4ZtBFuX7X4tFncmWizHhrqa0xvoAEl8hZFZ6+RjbAOzd9kDLfdHevLVv6z8VQusvY58GbAHPP0h4yd4PA0YsSeiLv1F7X7bCH6weZo16t42lVh4NrAS2XHqSOOvMyAWo="
    - DOCS_BRANCH="0.3.0"
    - GEN_APIDOCS="gradle javadoc"

after_success:
  - chmod a+x travis/build_clj.sh
  - ./travis/build_clj.sh
  - chmod a+x travis/post_build.sh
  - ./travis/post_build.sh
  
notifications:
  slack: puniverse:OsnbakHrYeTcLyalVgtUeI4F
