markdown: enhanced_kramdown
pygments: true
lsi: false
safe: false
baseurl: /comsat

kramdown:
  toc_levels: [1,2,3]
  use_coderay: false
  coderay:
    enable_coderay: false
    coderay_line_numbers: nil
    coderay_css: class

# Site globals used throughout docs.
project: Comsat
version: 0.1.0
github: puniverse/comsat
google_group: "https://groups.google.com/forum/#!forum/comsat-user"
tagline: "Scalable web application libraries"
ga_tracking_id: UA-25007319-2

