markdown: enhanced_kramdown
highlighter: pygments
lsi: false
safe: false
baseurl: /comsat

# Site globals used throughout docs.
project: Comsat
version: 0.4.0
github: puniverse/comsat
google_group: "https://groups.google.com/forum/#!forum/comsat-user"
tagline: "Scalable web application libraries"
ga_tracking_id: UA-25007319-2
code_dir: "../"
